### ISSUE TITLE
Can't add SSH ed25519 keys

### ISSUE THREAD

**Issue by renatoram** [fusiondirectory/fusiondirectory-plugins#17]
I noticed that the web interface sanity checks were refusing my ed25519 elliptic curve ssh keys.

Simply changing line 25 in fusiondirectory-plugins/ssh/personal/ssh/class_sshAccount.inc

from:
`protected $format = '/^([-[:alnum:]=",.]+\s+)?(disabled-)?(ssh-(dss|rsa)|ecdsa-sha2-nistp\d{3})\s+([[:alnum:]+\/.=]+)(\s+([[:graph:][:space:]]+))?\s*$/';`

to:
`protected $format = '/^([-[:alnum:]=",.]+\s+)?(disabled-)?(ssh-(dss|rsa|ed25519)|ecdsa-sha2-nistp\d{3})\s+([[:alnum:]+\/.=]+)(\s+([[:graph:][:space:]]+))?\s*$/';`

allowed me to fix the problem. Maybe consider adding it to a next release?

**Comment by renatoram** [comment]
Excellent, thanks!

**Comment by bilbo-the-hobbit** [comment]
hello @tanji and @renatoram ,

the code is now in the 1.3-dev due to release next week, you can test it ? you can install fusiondirectory 1.3-dev from here :
deb https://integration.fusiondirectory.org/repos/development/debian/fusiondirectory-dev-stretch/ stretch main or just take the patch from the ticket.

Cheers

**Comment by MCMic** [comment]
This is fixed in 1.3 (out soon)

**Comment by tanji** [comment]
I run the patch in production and it works fine, thanks for merging it :+1:
