### ISSUE TITLE
Dovecot & Cyrus plugins store master password in unprotected cleartext attribute

### ISSUE THREAD

**Issue by NightTsarina** [fusiondirectory/fusiondirectory-plugins#25]
**Describe the bug**
After configuring either plugin, I notice the master usename and password for the service are stored in an unprotected LDAP attribute, and there is no indication to the user about this fact.

With a standard LDAP configuration, anybody can retrieve these passwords, even without binding to the directory:

$ ldapsearch -x | egrep 'fd(Dovecot|Cyrus)Password:'

fdDovecotPassword: ***
fdCyrusPassword: ***

This is a huge security risk, and should be clearly documented and warned about in the UI. Plus, it is not clear to me what is the actual purpose of this master account access (seems to be only to verify the mail account exists?) and there is no way to disable this functionality, short of removing the plugin(s).

**Comment by NightTsarina** [comment]
Versions:

Debian testing
Fusiondirectory 1.3
Slapd 2.4.47

**Comment by MCMic** [comment]
You should not give full read access to random people on your LDAP, cyrus password is not the only sensible information in the LDAP.

I thought Debian only gave -x read right to root, no?

**Comment by NightTsarina** [comment]
Sorry, but that is not correct.

It is standard to give read access to most attributes in an LDAP directory, and that is how Debian ships by default, OpenLDAP upstream also has read enabled by default, among other systems.

Plus, putting cleartext passwords is never good security practice, much less when it is an administrative account that allows access to private email of anybody in the organisation!

So I stand by what I said, this is pretty serious. It should not be done like this in the first place, but if you are going to do it, you need to put a big fat warning about it. I bet most of your users are vulnerable to this attack without knowing it.

As a last point, considering that the dovecot plugin does not seem to give much functionality when dovecot talks to LDAP directly, I would discontinue this plugin and schema completetely.

**Comment by MCMic** [comment]
@NightTsarina As I said if you let read access on your LDAP to any user this will not be the only problem.

In Europe in most cases I expect it’s not even legal to let any user read other users information.

**Comment by NightTsarina** [comment]
@MCMic What other problems of this calibre are you thinking about? If your network is compromised by information contained in a directory, **those** seem like bigger problems to me.

Nevertheless, the bug I am reporting here is that passwords should never be stored in cleartext. And if you are going to do it, you really need to add warnings and mention this in the documentation. It is really a no-brainer.

**Comment by MCMic** [comment]
@NightTsarina All the fields edited through FusionDirectory are stored in the LDAP directory. We will not add a warning for each field in the documentation.
A lot of information in the LDAP is sensible, URLs, hosts, passwords, private information and so on. Mail methods are not an isolated case.

**Comment by NightTsarina** [comment]
OK. Nevermind, it is sad to see that security is not taken seriously. I had hoped to use fusiondirectory for my customer, but I can't trust a project that thinks that storing a cleartext password is the same as saving an URL or a hostname, and that refuses to document critical security information.

**Comment by kadogo** [comment]
Hello @NightTsarina 

From what I know there is no possibility to use an auth mechanism without giving the password in clear text. The server surely use the standard method that compare password + salt and the stored hash. With that mechanism I not think there is a proper way to avoid sending a clear text password.

If you know another method let us know by adding documentations or contributions about it.

Cheers.

**Comment by NightTsarina** [comment]
@kadogo The obvious choices would be saving it on the local config file, or not saving it at all.  Both reasonable choices.

I would definitely consider sending patches, like I do for every project I use, but from the discussion here it does not seem like that would be a fruitful and pleasant experience...

**Comment by kadogo** [comment]
Hello @NightTsarina 

I not think they would be the "obvious" choice. There at least 2 issues with it.

* Saving the password in a config file. It could be done but that can only be useful if **ONLY** FusionDirectory need to use them. It also means you start losing all the point of managing your infrastructure with your LDAP. Still with that solution it means you need to secure your server and your files correctly.

* Not saving it at all. It means not using the SIEVE possibility when you create a user and want the mailbox to be created on the mail server. Cyrus works like that, I don't know for Dovecot.

There is a possibility if the user have implemented fusiondirectory.secrets to encrypt the credentials that are in fusiondirectory.conf that are only readable by root. But you will have the same issue at my first point, it means that it will **ONLY** be useful for FusionDirectory use. Any other application that would need the password to make an operation will not work.

Using an LDAP for configuration and managing is the same of "pushing" configurations in your LDAP. Adding an ACL for forbidden peoples to read the all LDAP is easily done but the goal of FusionDirectory is to manage the LDAP. It's not his goal to take decision in place of the sysadmin like changing the LDAP because there would still be a risk involving the LDAP's data.

Cheers.
